name: Deploy Cloudflare Search

on:
  push:
    paths:
      - .github/scripts/cloudflare-search/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd .github/scripts/cloudflare-search && npm install --only=dev && cd ../../

      - name: Deploy with wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: cd .github/scripts/cloudflare-search && npm run deploy
